### ISSUE TITLE
Is there (planned) support for the container storage interface or CSI to facilitate hands-off data ingress?

### ISSUE THREAD

**Issue by compiaffe** [NVIDIA/ais-k8s#5]
When using e.g. Rook (https://rook.io/) code running in nodes does not need to care about the storage back-end. K8s simply attaches a volume and data is written. That is done by using the  `Container Storage Interface`: https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/ as implemented by e.g. ceph-csi: https://github.com/ceph/ceph-csi

Is there a similar component in ais-k8s? 

What would be the recommended way to put data into the system? Can this be done aistore agnostic?

As (simplified) background: We are building a video recorder for ML workloads and receive video data on a server/pod to store. With a CSI this is a simple disk write and the application doesn't need to care how data is actually stored.

With AIstore I seem to currently require aistore specific logic to achieve the same. e.g. using the ais client to upload fileparts.

Thanks for any insight :)

**Comment by alex-aizman** [comment]
No, there's no plan to provide CSI plugin. Similar to the majority, if not absolutely all, existing object and object-like storages, aistore provides both native and s3 compliant interfaces, with an additional simple extension dubbed "easy URL". For s3, look at docs/s3*.

As far as file, I actually removed FUSE-based extension fairly recently (379cac6b22586ec4f814c2927e495ccf30ed35a0) mostly due to general lack of interest. It may change in the future, but I hope it wont. 

But to answer your question, the way for us to provide something even less aistore-aware then your conventional HTTP `GET bucket/object` is integrating with ML frameworks. In that sense, we already made out first step towards PyTorch - google: aistore pytorch.
